---
title: "health_data"
output: html_document
---

```{r import load libraries}
library(gsheet)
library(readr)
library(readxl)
```

```{r import other libraries, warning = FALSE, message = FALSE}
library(tidyverse)
library(car)
library(lmtest)
library(sandwich)
library(stargazer)
library(tidyverse)
library(magrittr)
library(ggplot2)
library(dplyr)
library(patchwork)
```

health conditions:
8. chronic respiratory disease
5. asthma
1. % 65+
2. % smokers
3. % obesity
4. diabetes
6. heart disease mortality
7. stroke mortality



```{r}
# Load data from Yu-Chronic Respiratory Disease Mortality
# There are several sheets in this xlsx file. Relevant sheets/variables to pull:
# 1. Chronic respiratory diseases

chronic_respiratory_diesease <- read_excel('data/Yu-Chronic Respiratory Disease Mortality/IHME_USA_COUNTY_RESP_DISEASE_MORTALITY_1980_2014_NATIONAL_Y2017M09D26.XLSX',
                                           sheet = 'Chronic respiratory diseases')

asthma_death <- read_excel('data/Yu-Chronic Respiratory Disease Mortality/IHME_USA_COUNTY_RESP_DISEASE_MORTALITY_1980_2014_NATIONAL_Y2017M09D26.XLSX',
                           sheet = 'Asthma')
```


```{r}
# Load data from Yu-County Health Rankings
# Variables in dataset (confirm in documentation):
# Adult smoking (% smokers)
# Adult obesity (% adults with obesity)
# % 65 and older

county_health_rankings <- read_csv('data/Yu-County Health Rankings/analytic_data2021.csv')
```


```{r}
# Load diabetes data from Yu-Diabetes
# Diagnosed Diabetes; Total (Total); Adults Aged 20+ Years; Crude Number; U.S. Counties; 2017

# Edited the csv so that the column headers are in the top row
diabetes <- read_csv('data/Yu-Diabetes/DiabetesAtlasCountyData-Edited.csv')
```

```{r}
# Load data from Yu-Stroke and Heart Disease
heart_disease <- read_csv('data/Yu-Stroke and Heart Disease/all_heart_disease_deathrateper100k_allages_2016-2018.csv')
stroke <- read_csv('data/Yu-Stroke and Heart Disease/all_stroke_deathrateper100k_allages_2016-2018.csv')
```


```{r astha handling}
# Get asthma death data in usable format
# deaths per 100k, already normalized

# Select relevant columns: Location, FIPS, and 2014 mortality rate
asthma_death_2014_clean <-  asthma_death %>%
  select(...2, ...10)

# Rename columns and convert FIPS to integer
# take average mortality rate (delete confidence interval)
asthma_death_2014_clean <- asthma_death_2014_clean %>% 
  rename(
    FIPS = ...2,
    asthma_deaths_per100k = ...10
    ) %>%
  transform(
    FIPS = as.numeric(FIPS),
    asthma_deaths_per100k = as.numeric(substr(asthma_deaths_per100k, start = 1, stop = 4))
  )

# Remove top row
asthma_death_2014_clean <- asthma_death_2014_clean[-c(1), ]


summary(asthma_death_2014_clean)
```

```{r chronic respiratory disease handling}
# Get chronic respiratory disease death data in usable format
# deaths per 100k, already normalized

# Select relevant columns: Location, FIPS, and 2014 mortality rate
chronic_respiratory_diesease_2014_clean <-  chronic_respiratory_diesease %>%
  select(...2, ...10)

# Rename columns and convert FIPS to integer
# take average mortality rate (delete confidence interval)
chronic_respiratory_diesease_2014_clean <- chronic_respiratory_diesease_2014_clean %>%
  rename(
    FIPS = ...2,
    chronic_respiratory_disease_deaths_per100k = ...10
    ) %>%
  transform(
    FIPS = as.numeric(FIPS),
    chronic_respiratory_disease_deaths_per100k = as.numeric(substr(chronic_respiratory_disease_deaths_per100k, start = 1, stop = 4))
  )

# Remove top row
chronic_respiratory_diesease_2014_clean <- chronic_respiratory_diesease_2014_clean[-c(1), ]


summary(chronic_respiratory_diesease_2014_clean)
```


```{r}
# Variables:
# 1. % of adults with obesity
# 2. % of adults that smoke
# 3. % of adults that are 65+
# already normalized

# select relevant variables
# convert to numbers
county_health_rankings_clean <- county_health_rankings %>%
  select(
    `5-digit FIPS Code`,
    `Adult obesity raw value`,
    `Adult smoking raw value`, 
    `% 65 and older raw value`,
  ) %>%
  rename(
    FIPS = `5-digit FIPS Code`,
    obesity_percent = `Adult obesity raw value`,
    smoking_percent = `Adult smoking raw value`,
    over_65_percent = `% 65 and older raw value`
    ) %>%
  transform(
    FIPS = as.numeric(FIPS),
    obesity_percent = as.numeric(obesity_percent),
    smoking_percent = as.numeric(smoking_percent),
    over_65_percent = as.numeric(over_65_percent)
  )

# Remove top row
county_health_rankings_clean <- county_health_rankings_clean[-c(1), ]

summary(county_health_rankings_clean)
```

```{r diabetes cleaning}
# people diagnosed with diabetes
# needs to be normalized

# select appropriate columns
# convert to numbers
diabetes_clean <- diabetes %>%
  select(
    CountyFIPS,
    Number
  ) %>%
  rename(
    FIPS = CountyFIPS,
    num_diabetes_diagnosed = Number
  ) %>%
  transform(
    FIPS = as.numeric(FIPS),
    num_diabetes_diagnosed = as.numeric(num_diabetes_diagnosed)
  )

summary(diabetes_clean)
```


```{r heart disease}
# heart disease per 100k
# -1 values = NA
# already normalized

# select appropriate columns
# convert to numbers
heart_disease_clean <- heart_disease %>%
  select(
    cnty_fips,
    Value
  ) %>%
  rename(
    FIPS = cnty_fips,
    heart_disease_per100k = Value
  ) %>%
  transform(
    FIPS = as.numeric(FIPS),
    heart_disease_per100k = ifelse(as.numeric(heart_disease_per100k) > -1, as.numeric(heart_disease_per100k), NA)
  )

summary(heart_disease_clean)
```

```{r stroke}
# stroke per 100k
# -1 values = NA
# already normalized

# select appropriate columns
# convert to numbers
stroke_clean <- stroke %>%
  select(
    cnty_fips,
    Value
  ) %>%
  rename(
    FIPS = cnty_fips,
    stroke_per100k = Value
  ) %>%
  transform(
    FIPS = as.numeric(FIPS),
    stroke_per100k = ifelse(as.numeric(stroke_per100k) > -1, as.numeric(stroke_per100k), NA)
  )

summary(stroke_clean)
```


```{r produce final df}
all_health_data_clean <- diabetes_clean %>% merge(asthma_death_2014_clean, by = "FIPS", all.x = TRUE) %>%
  merge(chronic_respiratory_diesease_2014_clean, by = "FIPS", all.x = TRUE) %>%
  merge(county_health_rankings_clean, by = "FIPS", all.x = TRUE) %>%
  merge(heart_disease_clean, by = "FIPS", all.x = TRUE) %>%
  merge(stroke_clean, by = "FIPS", all.x = TRUE)
```


