---
title: "load_data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(gsheet)
library(readr)
library(readxl)
```

```{r}
# Load data about mask-wearing polices from the W203 spreadsheet
url_203data_masks <- 'https://docs.google.com/spreadsheets/d/1zu9qEWI8PsOI_i8nI_S29HDGHlIp2lfVMsGxpQ5tvAQ/edit#gid=1489353670'
mask_policy <- read.csv(text=gsheet2text(url_203data_masks,format='csv'),
                        stringsAsFactors=FALSE)
```

```{r}
# Load data about stay-at-home orders from the W203 spreadsheet
url_203data_stayathome <- 'https://docs.google.com/spreadsheets/d/1zu9qEWI8PsOI_i8nI_S29HDGHlIp2lfVMsGxpQ5tvAQ/edit#gid=1894978869'
stayathome_policy <- read.csv(text=gsheet2text(url_203data_stayathome,format='csv'),
                        stringsAsFactors=FALSE)
```

```{r}
# Load data about interstate travel quarantines from the W203 spreadsheet
url_203data_travel <- 'https://docs.google.com/spreadsheets/d/1zu9qEWI8PsOI_i8nI_S29HDGHlIp2lfVMsGxpQ5tvAQ/edit#gid=1383532126'
travel_policy <- read.csv(text=gsheet2text(url_203data_travel,format='csv'),
                        stringsAsFactors=FALSE)
```

```{r}
# Load county-level COVID case and death data from NY times
url_nytimes <- 'https://raw.githubusercontent.com/nytimes/covid-19-data/master/live/us-counties.csv'
cases_deaths <- read_csv(url(url_nytimes))
```

```{r}
# Load county-level data about icu beds from CovidCareMap (CCM)
url_covidcaremap <- 'https://raw.githubusercontent.com/covidcaremap/covid19-healthsystemcapacity/master/data/published/us_healthcare_capacity-county-CovidCareMap.csv'
icu_beds_ccm <- read_csv(url(url_covidcaremap))
```

```{r}
# Load data from Yu-Chronic Respiratory Disease Mortality
# There are several sheets in this xlsx file. Relevant sheets/variables to pull:
# 1. Chronic respiratory diseases
# 2. Asthma

chronic_respiratory_diesease <- read_excel('data/Yu-Chronic Respiratory Disease Mortality/IHME_USA_COUNTY_RESP_DISEASE_MORTALITY_1980_2014_NATIONAL_Y2017M09D26.XLSX',
                                           sheet = 'Chronic respiratory diseases')

asthma_death <- read_excel('data/Yu-Chronic Respiratory Disease Mortality/IHME_USA_COUNTY_RESP_DISEASE_MORTALITY_1980_2014_NATIONAL_Y2017M09D26.XLSX',
                           sheet = 'Asthma')

# Data cleaning that needs to happen:
# 1. Drop rows for individual states, U.S.
# 2. Make the first row the column names
# 3. I personally am inclined to only take the "Mortality Rate, 2014"
# 4. The data for each row I believe is some type of average + a confidence interval -->
#    We need to get rid of the confidence interval

# Other considerations:
# Should we use deaths from asthma...? maybe it would be better to find an asthma incidence rate
```


```{r}
# Load data from Yu-County Health Rankings
# Variables in dataset (confirm in documentation):
# 1.  Premature death
# 2.  Poor physical health days
# 3.  Poor mental health days
# 4.  Low birthweight (% low birthweight)
# 5.  Adult smoking (% smokers)
# 6.  Adult obesity (% adults with obesity)
# 7.  Food environment index
# 8.  Physical inactivity (% physically inactive)
# 9.  Access to exercise opportunities
# 10. Excessive drinking (% excessive drinking)
# 11. Alcohol-impaired driving deaths
# 12. Sexually transmitted infections
# 13. Teen births
# 14. Uninsured
# 15. Primary care physicians
# 16. Ratio of population to primary care physicians
# 17. Dentists
# 18. Ratio of population to dentists
# 19. Mental health providers
# 20. Ratio of population to mental health providers
# 21. Preventable hospital stays
# 22. Flu vaccinations
# 23. High school completion
# 24. Some college
# 25. Unemployment
# 26. Children in poverty (% children in poverty)
# 27. Income inequality
# 28. Air pollution - particulate matter raw value
# 29. Drinking water violations
# 30. Life expectancy
# 31. Diabetes prevalence
# 32. Food insecurity
# 33. Limited access to healthy foods
# 34. High school graduation raw value
# 35. Median household income
# 36. Population
# 37. % 65 and older
# 38. % rural
# and a bunch of others that i just did not have the energy to write down

county_health_rankings <- read_csv('data/Yu-County Health Rankings/analytic_data2021.csv')
```
```{r}
# Load diabetes data from Yu-Diabetes
# Diagnosed Diabetes; Total (Total); Adults Aged 20+ Years; Crude Number; U.S. Counties; 2017

# Edited the csv so that the column headers are in the top row
diabetes <- read_csv('data/Yu-Diabetes/DiabetesAtlasCountyData-Edited.csv')
```

```{r}
# Load data from Yu-Health Professional Shortages
# Not loading data (yet) from Medically Underserved Areas

health_prof_shortages <- read_csv('data/Yu-Health Professional Shortages/Health Professional Shortage Areas/BCD_HPSA_FCT_DET_PC.csv')
```

```{r}
# Load data from Yu-ICU Beds
icu_beds_khn <- read_excel('data/Yu-ICU Beds/KHN_ICU_bed_county_analysis_2.xlsx')
```

```{r}
# Load data from Yu-Poverty
# Poverty estimates for the U.S., States, and counties, 2019																																														
# Source: U.S. Department of Commerce, Bureau of the Census, Small Area Income and Poverty Estimates (SAIPE) Program. 																																														
# For definitions of rural classifications, see the USDA, Economic Research Service webpage "Rural Classifications" in the "Rural Economy & Population" topic. Variable descriptions (column names) are found in the second tab in this workbook.																																														
# This table was prepared by USDA, Economic Research Service. Data as of January 5, 2021. Contact: Kathleen Kassel, USDA/ERS.																																														
# Edited excel file to put column names in first row

poverty <- read_excel('data/Yu-Poverty/PovertyEstimates-Edited.xls')
```


```{r}
# Load data from Yu-Social Vulnerability Index
# svi = social vulnerability index
svi <-  read_csv('data/Yu-Social Vulnerability Index/SVI2018_US_COUNTY.csv')
```

```{r}
# Load data from Yu-Stroke and Heart Disease
heart_disease <- read_csv('data/Yu-Stroke and Heart Disease/all_heart_disease_deathrateper100k_allages_2016-2018.csv')
stroke <- read_csv('data/Yu-Stroke and Heart Disease/all_stroke_deathrateper100k_allages_2016-2018.csv')
```


